---

user: ubuntu

allow_moc_ssh: true
allow_moc_p2p: true

NODE_FULLNAME: "moc"
NODE_ADMIN_EMAIL: ""
NODE_PWD: "node.pwd" # don't change this one

NETSTATS_SERVER: ""
NETSTATS_SECRET: ""

MOC_ADDRESS: "0x6f4ed9f807b96ca83696107f56c0091c5c378d41"
MOC_KEYPASS: ""
MOC_KEYFILE: ""

SCRIPTS_MOC_BRANCH: "master"
GENESIS_NETWORK_NAME: "FuseNetwork"
MAIN_REPO_FETCH: "ColuLocalNetwork"

BLK_GAS_LIMIT: "6700000"

username: "moc"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"

moc_archive: "off"

reboot_after_completion: false
install_debug_tools: "no"
install_firewall: true