---

GENESIS_NETWORK_NAME: "FuseNetwork"
PARITY_BIN_LOC: "https://releases.parity.io/ethereum/v2.2.5/x86_64-unknown-linux-gnu/parity"
PARITY_BIN_SHA256: "5a4c8d947feadc48cae1a85f58845b3129d73f96cc7c13df2df8a780584da947"
ORCHESTRATOR_BIN_LOC: ""                                                                                                                
ORCHESTRATOR_BIN_SHA256: ""
 
validator_archive: "off"
bootnode_archive: "off"
moc_archive: "off"
bootnode_orchestrator: "off"

username: "poa"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"
