---

username: "poa"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"

GENESIS_NETWORK_NAME: "PoA"
MAIN_REPO_FETCH: "ColuLocalNetwork"
GENESIS_BRANCH: "master"

spec_json: ""
bootnodes_txt: ""