---

user: ubuntu

allow_explorer_ssh: true
allow_explorer_p2p: true
allow_explorer_http: true

username: "explorer"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"

nginx_headers: "off"
PROXY_PORT: "3000"

MAIN_REPO_FETCH: "ColuLocalNetwork"
MOC_ADDRESS: "0x6f4ed9f807b96ca83696107f56c0091c5c378d41"

explorer_version: "acee07c"

reboot_after_completion: false
install_debug_tools: "no"
install_firewall: true