---

user: ubuntu

allow_blockscout_ssh: true
allow_blockscout_p2p: true
allow_blockscout_http: false

username: "blockscout"
users:
- name: "{{ username }}"
home: "/home/{{ username }}"

MAIN_REPO_FETCH: "ColuLocalNetwork"
MOC_ADDRESS: "0x6f4ed9f807b96ca83696107f56c0091c5c378d41"

reboot_after_completion: true
install_debug_tools: "no"
install_firewall: false

#Use branch with styles for specified network
blockscout_version: "{{ 'f1aafe7406' if GENESIS_BRANCH == 'sokol' else 'a8c4c72c54' }}"
db_user: "blockscout"
PROXY_PORT: "4000"